# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'case.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# import xlrd
# from pyppeteer import launch
# import pyppeteer
# from lxml import etree
# import asyncio

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableView,QTableWidget
from PyQt5.QtWidgets import QTableWidgetItem
from PyQt5.QtCore import *
import time,requests
import threading

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1022, 741)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 60, 911, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(350, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(250, 50))
        self.pushButton_2.setAutoRepeatDelay(300)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 170, 911, 511))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(500, 1000))
        self.tableWidget_2.setRowCount(500)
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(25)
        self.horizontalLayout_2.addWidget(self.tableWidget_2)
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.tableWidget.setRowCount(200)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.horizontalLayout_2.addWidget(self.tableWidget)

        self.tableWidget.setEditTriggers(QTableWidget.NoEditTriggers)
        self.tableWidget_2.setEditTriggers(QTableWidget.NoEditTriggers)

        self.retranslateUi(Dialog)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_3.setText(_translate("Dialog", "一键申请"))
        self.pushButton_2.setText(_translate("Dialog", "获取邮箱"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "姓名"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "邮箱"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "状态"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "学生号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "学生邮箱"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "邮箱密码"))



    def update_item_data(self, data):
        """更新内容"""


        row = data[0]
        col = data[1]
        detail = data[2]
        #print(detail)
        self.tableWidget.setRowCount(row)

        self.tableWidget.clear()
        self.tableWidget.setHorizontalHeaderLabels(['学生号','学生邮箱','邮箱密码'])
        for i in range(row-1):
            for j in range(col):
                a = detail[i][j]
                self.tableWidget.setItem(i, j, QTableWidgetItem(str(a)))


    def update_item_data2(self, data):
        """更新内容"""


        row = data[0]
        col = data[1]
        detail = data[2]
        self.tableWidget_2.setRowCount(row)
        self.tableWidget_2.clear()
        self.tableWidget_2.setHorizontalHeaderLabels(['姓名', '邮箱', '状态'])
        for i in range(row-1):
            for j in range(col):
                a = detail[i][j]
                self.tableWidget_2.setItem(i, j, QTableWidgetItem(str(a)))



    def click_success2(self):

        self.pb2 = PushButton2Thread()

        self.pb2.start()
        self.pushButton_2.setEnabled(False)


    def click_success3(self):

        self.pb3 = PushButton3Thread()
        self.pb3.start()
        self.pushButton_3.setEnabled(False)




class PushButton2Thread(QThread):
    #signal = pyqtSignal(str)
    print(2)
    # def __init__(self):
    #     super.__init__()

    def run(self):
        while True:

            print('获取邮件')
            #get_stu_edu.main()
            requests.get('http://127.0.0.1:8000/getemail')
            time.sleep(60)


class PushButton3Thread(QThread):


    def run(self):
        print('一键申请')
        while True:
            threads = []

            def a():
                print('开始获取用户信息')
                requests.get('http://127.0.0.1:8000/getuser')
                time.sleep(30)
            threads.append(threading.Thread(target=a))
            #requests.get('http://127.0.0.1:8000/getuser')



            def b():
                print('开始申请学生信息')
                requests.get('http://127.0.0.1:8000/apply')
            threads.append(threading.Thread(target=b))
            #requests.get('http://127.0.0.1:8000/apply')


            def c():
                print('开始注册学生信息')
                requests.get('http://127.0.0.1:8000/register')
            threads.append(threading.Thread(target=c))
            #requests.get('http://127.0.0.1:8000/register')

            for t in threads:
                t.start()

            time.sleep(600)







